baseURL = "https://osowoso.github.io/clayto-hugo/"
languageCode = "en-us"
title = "clayto"

email = "mwc@clayto.com"

# theme = "hugo_theme_pickles"
theme = "palebluepixel"

# relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true

# black friday markdown parsing config
[blackfriday]
# laxHtmlBlocks allows empty lines inside HTML tags, such as an embedded script or style tag.
extensions = ["laxHtmlBlocks"]
fractions = false

# Copyright notice. This is displayed in the footer.
copyright = "&copy; Copyright 2013-2018 Michael Clayton"

# [taxonomies]
#   category = "projects"
#   tag = "tags"

[permalinks]
    categories = "/:slug/"
    post = "/:year/:month/:title/"
    posts = "/:year/:month/:title/"
    photo = "/photos/:year/:month/:title/"
    photos = "/photos/:year/:month/:title/"
    "/" = "/:year/:month/:filename/"

[params]
  paginate = 12
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "mwcz"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "mwcz"
  # gitlab = "Your GitLab username"
  # npm = "Your npm username"
  codepen = "mwcz"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  vimeo = "mwcz"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  #author = "Michael Clayton"
  authorwebsite = "clayto.com"
  avatar = false
  contact = "mwc@clayto.com"
  #bio = "a primitive lifeform trapped in a losing battle with entropy and confirmation bias."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Creative coding and web stuff."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "BLOG"
    url = "/"
    weight = 1

#[[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    weight = 2

[[menu.main]]
    name = "DEMOS"
    url = "/demos"
    weight = 1

[[menu.main]]
    name = "GAMES"
    url = "/games"
    weight = 1

#[[menu.main]]
#    name = "Tags"
#    url = "/tags"
#    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
  endLevel = 4
  startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
